// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "A63.hpp"
// tests for exercise 1
TEST_CASE("Ex1", "[example]")
{
	REQUIRE(getsum(3));
}
// tests for exercise 2
TEST_CASE("Ex2", "[example]")
{
	REQUIRE(getsum(5));
}